ALTER TABLE `Subscription`
  MODIFY COLUMN `billingCycle` ENUM('MONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'YEARLY', 'WEEKLY', 'CUSTOM') NOT NULL;

ALTER TABLE `SubscriptionPriceHistory`
  MODIFY COLUMN `billingCycle` ENUM('MONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'YEARLY', 'WEEKLY', 'CUSTOM') NOT NULL;
