ALTER TABLE `PaymentMethod`
  MODIFY COLUMN `type` ENUM(
    'CREDIT_CARD',
    'DEBIT_CARD',
    'PREPAID_CARD',
    'BANK',
    'BANK_TRANSFER',
    'CONVENIENCE_STORE',
    'CARRIER_BILLING',
    'PAYPAY',
    'RAKUTEN_PAY',
    'D_BARAI',
    'AU_PAY',
    'MERPAY',
    'LINE_PAY',
    'APPLE_PAY',
    'GOOGLE_PAY',
    'AMAZON_PAY',
    'PAYPAL',
    'RAKUTEN_EDY',
    'SUICA',
    'PASMO',
    'NANACO',
    'WAON',
    'ID',
    'QUICPAY',
    'INVOICE',
    'CASH',
    'OTHER'
  ) NOT NULL;
